# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
# development:



development:
  secret_key_base: f0a302938a990fc971a59073d97f05c5d7027e8928701221d622ff4495ec0c2491ed9724f83bd55c331b6af1f1c4f7a27a0f372b3e447cdbdf3522f4242279b1
  facebook_app_id: 406590146201026
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: f0a302938a990fc971a59073d97f05c5d7027e8928701221d622ff4495ec0c2491ed9724f83bd55c331b6af1f1c4f7a27a0f372b3e447cdbdf3522f4242279b1
  facebook_app_id: 406590146201026
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f0a302938a990fc971a59073d97f05c5d7027e8928701221d622ff4495ec0c2491ed9724f83bd55c331b6af1f1c4f7a27a0f372b3e447cdbdf3522f4242279b1
  facebook_app_id: 406590146201026
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
